type = "checkout_ui"
name = "resident-id"


extension_points = [
  'Checkout::DeliveryAddress::RenderBefore',
  'Checkout::Contact::RenderAfter',
  'Checkout::Actions::RenderBefore'
]

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"
